### ISSUE TITLE
Getting an error about packet transmission line

### ISSUE THREAD

**Issue by greyhoundforty** [richardimaoka/ping-to-json#1]
When running the script I am getting an error about the packet transmission line not matching what is expected, but it seems to match up from what I can tell:

```
❯ ping -c 5 google.com | ping-to-json/ping_to_json.sh

ERROR: '5 packets transmitted' is not in the form of '** packets transmitted', from the below summary line:
>5 packets transmitted, 5 received, 0% packet loss, time 4048ms
ERROR: RTT summary line is not found, which is like '** packets transmitted, ** received, *% packet loss, time ****ms'
```

**Comment by greyhoundforty** [comment]
This appears like it may be related to ZSH actually as I tried on a vanilla Ubuntu server and it worked just fine. Closing.

**Comment by Corruptsector** [comment]
I get the same issue with popOS 20.04.

ping -c 4 www.google.com | ./ping_to_json.sh
ERROR: '4 packets transmitted' is not in the form of '** packets transmitted', from the below summary line:
>4 packets transmitted, 4 received, 0% packet loss, time 3004ms
ERROR: RTT summary line is not found, which is like '** packets transmitted, ** received, *% packet loss, time ****ms'

**Comment by Ahacad** [comment]
Same problem on Google Cloud server, Ubuntu 18.04.

I remove manually the test code in `rtt_summary.sh` and the script still works and gives correct result.
